// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          uuid.UUID
	Name        string
	Email       string
	Password    string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Cpf         string
	PhoneNumber string
	Age         int32
}
