services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: database_register
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=web_register
    volumes:
      - register_db:/bitnami/postgresql
volumes:
  register_db:
    driver: local
